#$(info include.mk)

ALLINC += ${MODULE_SRC_DIR}/${MODULE}.h
MODULE_DEPS += ${MODULE_BUILD_ELF}

MODULE_FILEDEPS += \
	${MODULE_BUILD_ELF} \
	/lib/${MODULE}.elf

${MODULE_BUILD_ELF} : ${MODULE_SRC_DIR}/*
	@mkdir -p "${MODULE_BUILD_DIR}"
	@make -f "${MODULE_SRC_DIR}/Makefile" -C "${MODULE_BUILD_DIR}" VPATH="${MODULE_SRC_DIR}" all
