#define object files in the module

MOD_PRE = header_pre.h

MOD_OBJS = \
	   lmnts.o \
       elements/dsp/multistage_envelope.o \
       elements/dsp/ominous_voice.o \
       elements/dsp/resonator.o \
       elements/dsp/string.o \
       elements/dsp/tube.o \
       elements/dsp/exciter.o \
       elements/elements_resources.o \
       elements/dsp/part.o \
       elements/dsp/voice.o 

