#define object files in the module

MOD_PRE = header_pre.h

MOD_OBJS = \
    braids/braids_resources.o \
    braids/analog_oscillator.o \
    braids/digital_oscillator.o \
    braids/macro_oscillator.o 



