#define object files in the module

MOD_PRE = header_pre.h

MOD_OBJS = \
       streams/streams_resources.o \
       streams/compressor.o \
       streams/envelope.o \
       streams/follower.o \
       streams/lorenz_generator.o \
       streams/processor.o \
       streams/svf.o \
       streams/vactrol.o 



